function createfigure(xdata1, ydata1, zdata1, xdata2, ydata2, zdata2)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1, XDATA2, YDATA2, ZDATA2)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  XDATA2:  surface xdata
%  YDATA2:  surface ydata
%  ZDATA2:  surface zdata

%  Auto-generated by MATLAB on 18-Oct-2018 11:42:06

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.334659090909091 0.793174606123579]);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'LineStyle','none');

% Create xlabel
xlabel({'Utility $u$'},'HorizontalAlignment','center','FontSize',20,...
    'Rotation',40,...
    'Interpreter','latex');

% Create zlabel
zlabel('Time $t$','FontSize',20,'Interpreter','latex');

% Create title
title('(a) $a=0.6$','FontSize',20,'Interpreter','latex');

% Create ylabel
ylabel({'Polarization $x(t)$'},'FontSize',20,'Rotation',-28,...
    'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.1 0.9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 1]);
view(axes1,[130 55]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'ZDir','reverse');
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.570340909090909 0.11 0.334659090909091 0.793174606123579]);
hold(axes2,'on');

% Create surf
surf(xdata2,ydata2,zdata2,'Parent',axes2,'LineStyle','none');

% Create xlabel
xlabel('Utility $u$','FontSize',20,'Rotation',-59,'Interpreter','latex');

% Create zlabel
zlabel('Time $t$','FontSize',20,'Interpreter','latex');

% Create title
title('(b) $a=2.5$','FontSize',20,'Interpreter','latex');

% Create ylabel
ylabel('Polarization $x(t)$','FontSize',20,'Rotation',11,...
    'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.1 0.9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[0 1]);
view(axes2,[70 55]);
box(axes2,'on');
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'ZDir','reverse');
